/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;
import NSBMCourseEnrollmentSystem_DB_connection.DB_connection;
import NSBMCourseEnrollmentSystem_control.Subject_controll;
import NSBMCourseEnrollmentSystem_model.Subject;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lahiru Dulanjaya
 */
public class Admin_Update_Subject extends javax.swing.JFrame {
  
    /**
     * Creates new form Find
     */
    public Admin_Update_Subject() {
        initComponents();
        try {
            fillcombo();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Update_Subject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stu_id = new javax.swing.JTextField();
        update = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        sem = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        delete = new javax.swing.JToggleButton();
        change = new javax.swing.JToggleButton();
        reset = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JToggleButton();
        add = new javax.swing.JToggleButton();
        no = new javax.swing.JRadioButton();
        yes = new javax.swing.JRadioButton();
        course = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Subject");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Insert Subject Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 158, 42));

        stu_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_idActionPerformed(evt);
            }
        });
        jPanel1.add(stu_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 200, 42));

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 120, 40));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel5.setText("Course");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 180, 40));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel7.setText("Subject Credit");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, 40));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel11.setText("year");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 180, 40));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel13.setText("Semester");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 180, 40));

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel15.setText("Compulsory");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 180, 40));

        jLabel21.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel21.setText("Subject Code");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, 40));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 300, 30));
        jPanel1.add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 300, 30));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 300, 30));

        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });
        jPanel1.add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 300, 30));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 300, 30));

        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 120, 40));

        change.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        change.setText("Search");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 120, 40));

        reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 40));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel3.setText("Subject Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 40));

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 80, 40));

        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 120, 40));

        no.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(no);
        no.setText("No");
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        yes.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(yes);
        yes.setText("Yes");
        jPanel1.add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         Subject us =new Subject();
        us.setName(name.getText());
        us.setSubject_code(ID.getText());
        
        if(yes.isSelected()){
            us.setCompulsory(true);
        }
        else {
            us.setCompulsory(false);
        }
        us.setCredits(Integer.parseInt(credit.getText()));
        us.setCourse(course.getSelectedItem().toString());
        us.setYear(Integer.parseInt(year.getText()));
        us.setSemester(Integer.parseInt(sem.getText()));
         
        try {
            Subject_controll.Subject_update(us);
            JOptionPane.showMessageDialog(this,"Updated Success");
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Update_Subject.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
            String id = stu_id.getText();
        try {
            Subject_controll.Subject_delete(id);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Update_Subject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
                String id = stu_id.getText();
                
        try{
            Subject us =Subject_controll.getsub(id);
            if (us!=null){
                ID.setText(us.getSubject_code());
                name.setText(us.getName());
                
                credit.setText(Integer.toString(us.getCredits()));
                
                course.setSelectedItem(us.getCourse());
                year.setText(Integer.toString(us.getYear()));
                
                
                
                sem.setText(Integer.toString(us.getSemester()));
                if(us.isCompulsory()){
                    yes.setSelected(rootPaneCheckingEnabled);
                }
                else{
                    no.setSelected(rootPaneCheckingEnabled);
                }
                
                
                
            }
            else{
                JOptionPane.showMessageDialog(this,"There is no Subject");
            }

        }   catch (HeadlessException | SQLException ex) {
            Logger.getLogger(Admin_Update_Subject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
                ID.setText(null);
                name.setText(null);                
                credit.setText(null);               
                year.setText(null);
                course.setSelectedIndex(-1);
                sem.setText(null);               
                
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     register_option al=new register_option(); 
        this.dispose();
        al.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Subject us =new Subject();
        us.setName(name.getText());
        us.setSubject_code(ID.getText());
        
        if(yes.isSelected()){
            us.setCompulsory(true);
        }
        else {
            us.setCompulsory(false);
        }
        us.setCredits(Integer.parseInt(credit.getText()));
        us.setCourse(course.getSelectedItem().toString());
        us.setYear(Integer.parseInt(year.getText()));
        us.setSemester(Integer.parseInt(sem.getText()));
        

        try {
            Subject_controll.add(us);
            JOptionPane.showMessageDialog(this,"Success");
        } catch (HeadlessException | SQLException ex) {

            JOptionPane.showMessageDialog(this,ex);
        }

    }//GEN-LAST:event_addActionPerformed

    private void stu_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_idActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Update_Subject().setVisible(true);
            }
        });
    }
    private void fillcombo() throws SQLException{
        
         String sql1="Select Course_Id from courses";
          Connection con =DB_connection.getConnection();
          PreparedStatement pst = con.prepareStatement(sql1);
         ResultSet rs = pst.executeQuery();
         
         while(rs.next()){
             String cour = rs.getString("Course_Id");
             course.addItem(cour);
         }
         
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JToggleButton add;
    private javax.swing.JToggleButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton change;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField credit;
    private javax.swing.JToggleButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton no;
    private javax.swing.JToggleButton reset;
    private javax.swing.JTextField sem;
    private javax.swing.JTextField stu_id;
    private javax.swing.JToggleButton update;
    private javax.swing.JTextField year;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

}
