/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lahiru Dulanjaya
 */
public class Admin_Postgraduate extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Postgraduate
     */
    public Admin_Postgraduate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JToggleButton();
        find = new javax.swing.JToggleButton();
        show = new javax.swing.JToggleButton();
        add_assign = new javax.swing.JToggleButton();
        add_exm = new javax.swing.JToggleButton();
        add_final = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setText("Add Student");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 140, 49));

        find.setText("Find Student");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 150, 50));

        show.setText("Show All Students");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 49));

        add_assign.setText("Add Assignment Marks");
        add_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_assignActionPerformed(evt);
            }
        });
        getContentPane().add(add_assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, 50));

        add_exm.setText("Add Exam Marks");
        add_exm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_exmActionPerformed(evt);
            }
        });
        getContentPane().add(add_exm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 150, 50));

        add_final.setText("Add Final Marks");
        add_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_finalActionPerformed(evt);
            }
        });
        getContentPane().add(add_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 140, 50));

        jToggleButton5.setText("Back");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 110, 30));

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/Master.jpg"))); // NOI18N
        jLabel1.setText("Manage Postgraduate Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 550, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        {
            this.dispose();
            Register_Postgraduate rg =new Register_Postgraduate();
            rg.setVisible(true);
        }
    }//GEN-LAST:event_addActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        this.dispose();
        Update_Postgraduate fd =new Update_Postgraduate();
        fd.setVisible(true);
    }//GEN-LAST:event_findActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        this.dispose();
        Show_postgraduate sh = new Show_postgraduate();
        sh.setVisible(true);
    }//GEN-LAST:event_showActionPerformed

    private void add_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_assignActionPerformed
        this.dispose();
        try {
            Assignment_marks am =new Assignment_marks();
            am.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Undergraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_assignActionPerformed

    private void add_exmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_exmActionPerformed
        try {
            this.dispose();
            Exam_Marks em =new Exam_Marks();
            em.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Postgraduate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_exmActionPerformed

    private void add_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_finalActionPerformed
        Add_Final ap =new Add_Final();
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_add_finalActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        register_option ro=new register_option();
        this.dispose();
        ro.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Postgraduate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton add;
    private javax.swing.JToggleButton add_assign;
    private javax.swing.JToggleButton add_exm;
    private javax.swing.JToggleButton add_final;
    private javax.swing.JToggleButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton show;
    // End of variables declaration//GEN-END:variables
}
