/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;

import NSBMCourseEnrollmentSystem_DB_connection.DB_connection;
import NSBMCourseEnrollmentSystem_control.Assignment_controll;
import NSBMCourseEnrollmentSystem_model.Assignment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lahiru Dulanjaya
 */
public class Get_Assignment_Grade extends javax.swing.JFrame {

    /**
     * Creates new form Assignment_Marks
     */
    public Get_Assignment_Grade() throws SQLException {
        initComponents();
        filcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grade_table = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        getresult = new javax.swing.JToggleButton();
        subject_code = new javax.swing.JComboBox<>();
        back = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Assignment Grades");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 220, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Addmission Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Subject code");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, 30));

        grade_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ASSIGNMENT", "GRADE", "MARKS"
            }
        ));
        jScrollPane1.setViewportView(grade_table);
        if (grade_table.getColumnModel().getColumnCount() > 0) {
            grade_table.getColumnModel().getColumn(0).setMinWidth(20);
            grade_table.getColumnModel().getColumn(1).setMinWidth(100);
            grade_table.getColumnModel().getColumn(1).setMaxWidth(100);
            grade_table.getColumnModel().getColumn(2).setMinWidth(100);
            grade_table.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 560, 90));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 210, 30));

        getresult.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        getresult.setText("Get Result");
        getresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getresultActionPerformed(evt);
            }
        });
        getContentPane().add(getresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 40));

        subject_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_codeActionPerformed(evt);
            }
        });
        getContentPane().add(subject_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, 30));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 150, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        try {
            filcombo();
        } catch (SQLException ex) {
            Logger.getLogger(Get_Assignment_Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_idActionPerformed

    private void getresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getresultActionPerformed
        try {
            ArrayList<Assignment> result_list =Assignment_controll.getall(id.getText(),subject_code.getSelectedItem().toString());
            DefaultTableModel tb2 = (DefaultTableModel) grade_table.getModel();
            tb2.setRowCount(0);
            for(Assignment as: result_list){
                Object[] Data={as.getName(),as.getMarks(),as.getGrade()};
                tb2.addRow(Data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Get_Assignment_Grade.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_getresultActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        Student_Ability ua =new Student_Ability();
        ua.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void subject_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject_codeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Get_Assignment_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Get_Assignment_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Get_Assignment_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Get_Assignment_Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Get_Assignment_Grade().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Get_Assignment_Grade.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
       
    }
       public void filcombo() throws SQLException{
           subject_code.removeAllItems();//remove all elements in "subject_code" combo box"
           Connection con =DB_connection.getConnection();
           String sql ="select Subject_Code from assignment";
           PreparedStatement ps = con.prepareStatement(sql);
           
           ResultSet rs = ps.executeQuery();
           while(rs.next()){
               subject_code.addItem(rs.getString(1));
           }
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton getresult;
    private javax.swing.JTable grade_table;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> subject_code;
    // End of variables declaration//GEN-END:variables
}
