/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;

/**
 *
 * @author Lahiru Dulanjaya
 */
public class register_option extends javax.swing.JFrame {
    
    /**
     * Creates new form register_option
     */
    public register_option() {
        initComponents();
    }
    public static int option=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        postgraduate = new javax.swing.JToggleButton();
        undergraduate = new javax.swing.JToggleButton();
        lec = new javax.swing.JToggleButton();
        instructor = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        sub = new javax.swing.JToggleButton();
        payment = new javax.swing.JToggleButton();
        send_mails = new javax.swing.JToggleButton();
        allocation = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postgraduate.setBackground(new java.awt.Color(102, 102, 102));
        postgraduate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        postgraduate.setForeground(new java.awt.Color(255, 255, 255));
        postgraduate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/master'.jpg"))); // NOI18N
        postgraduate.setText("Postgraduate ");
        postgraduate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        postgraduate.setOpaque(true);
        postgraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgraduateActionPerformed(evt);
            }
        });
        jPanel1.add(postgraduate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 210, 70));

        undergraduate.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/stu.jpg"))); // NOI18N
        undergraduate.setText("Undergraduate ");
        undergraduate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate.setBorderPainted(false);
        undergraduate.setFocusCycleRoot(true);
        undergraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduateActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 70));

        lec.setBackground(new java.awt.Color(102, 102, 102));
        lec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lec.setForeground(new java.awt.Color(255, 255, 255));
        lec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/instructor (1).jpg"))); // NOI18N
        lec.setText("Lecturers");
        lec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lec.setFocusCycleRoot(true);
        lec.setOpaque(true);
        lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecActionPerformed(evt);
            }
        });
        jPanel1.add(lec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 220, 60));

        instructor.setBackground(new java.awt.Color(102, 102, 102));
        instructor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructor.setForeground(new java.awt.Color(255, 255, 255));
        instructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/lec1.jpg"))); // NOI18N
        instructor.setText("Instructors");
        instructor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        instructor.setFocusCycleRoot(true);
        instructor.setOpaque(true);
        instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorActionPerformed(evt);
            }
        });
        jPanel1.add(instructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 210, 70));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 120, 40));

        sub.setBackground(new java.awt.Color(102, 102, 102));
        sub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/sub1.jpg"))); // NOI18N
        sub.setText("Subjects");
        sub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sub.setFocusCycleRoot(true);
        sub.setOpaque(true);
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, 60));

        payment.setBackground(new java.awt.Color(102, 102, 102));
        payment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        payment.setForeground(new java.awt.Color(255, 255, 255));
        payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/payment1.jpg"))); // NOI18N
        payment.setText("Payment");
        payment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payment.setFocusCycleRoot(true);
        payment.setOpaque(true);
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, 60));

        send_mails.setBackground(new java.awt.Color(102, 102, 102));
        send_mails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        send_mails.setForeground(new java.awt.Color(255, 255, 255));
        send_mails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/ema.jpg"))); // NOI18N
        send_mails.setText("Send Mails");
        send_mails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        send_mails.setFocusCycleRoot(true);
        send_mails.setOpaque(true);
        send_mails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_mailsActionPerformed(evt);
            }
        });
        jPanel1.add(send_mails, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 210, 60));

        allocation.setBackground(new java.awt.Color(102, 102, 102));
        allocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        allocation.setForeground(new java.awt.Color(255, 255, 255));
        allocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/gI_93340_time-tracking-icon.jpg"))); // NOI18N
        allocation.setText("Class Allocation");
        allocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        allocation.setFocusCycleRoot(true);
        allocation.setOpaque(true);
        allocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocationActionPerformed(evt);
            }
        });
        jPanel1.add(allocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 250, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void undergraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduateActionPerformed
        Home.student=1;
        this.dispose();
        Admin_Undergraduate ad =new Admin_Undergraduate();
        ad.setVisible(true);
        
    }//GEN-LAST:event_undergraduateActionPerformed

    private void lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecActionPerformed
       Home.student=3;
        this.dispose();
        Admin_Lecturer ap = new Admin_Lecturer();
        ap.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_lecActionPerformed

    private void instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorActionPerformed
        Home.student=4;
        this.dispose();
        Admin_Instructor ap = new Admin_Instructor();
        ap.setVisible(true);
    }//GEN-LAST:event_instructorActionPerformed

    private void postgraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgraduateActionPerformed
        Home.student=2;
        this.dispose();
        Admin_Postgraduate ap = new Admin_Postgraduate();
        ap.setVisible(true);
    }//GEN-LAST:event_postgraduateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home hm =new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        Admin_Update_Subject up =new Admin_Update_Subject();
        this.dispose();
        up.setVisible(true);
    }//GEN-LAST:event_subActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
       this.dispose();
       Payment ww =new Payment();
       ww.setVisible(true);
    }//GEN-LAST:event_paymentActionPerformed

    private void send_mailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_mailsActionPerformed
       this.dispose();
       Email e =new Email();
       e.setVisible(true);
    }//GEN-LAST:event_send_mailsActionPerformed

    private void allocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocationActionPerformed
       Time_table t =new Time_table();
       t.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_allocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton allocation;
    private javax.swing.JToggleButton instructor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton lec;
    private javax.swing.JToggleButton payment;
    private javax.swing.JToggleButton postgraduate;
    private javax.swing.JToggleButton send_mails;
    private javax.swing.JToggleButton sub;
    private javax.swing.JToggleButton undergraduate;
    // End of variables declaration//GEN-END:variables
}
