/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;

/**
 *
 * @author Lahiru Dulanjaya
 */
public class register_option extends javax.swing.JFrame {
    
    /**
     * Creates new form register_option
     */
    public register_option() {
        initComponents();
    }
    public static int option=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        undergraduate = new javax.swing.JToggleButton();
        undergraduate1 = new javax.swing.JToggleButton();
        undergraduate3 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        undergraduate4 = new javax.swing.JToggleButton();
        undergraduate5 = new javax.swing.JToggleButton();
        undergraduate6 = new javax.swing.JToggleButton();
        undergraduate7 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(102, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Postgraduate Student");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToggleButton1.setOpaque(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 310, 60));

        undergraduate.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate.setText("Undergraduate Student");
        undergraduate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate.setBorderPainted(false);
        undergraduate.setFocusCycleRoot(true);
        undergraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduateActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 60));

        undergraduate1.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate1.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate1.setText("Lecturers");
        undergraduate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate1.setFocusCycleRoot(true);
        undergraduate1.setOpaque(true);
        undergraduate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduate1ActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 310, 60));

        undergraduate3.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate3.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate3.setText("Instructors");
        undergraduate3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate3.setFocusCycleRoot(true);
        undergraduate3.setOpaque(true);
        undergraduate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduate3ActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 310, 60));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 120, 40));

        undergraduate4.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate4.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate4.setText("Subjects");
        undergraduate4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate4.setFocusCycleRoot(true);
        undergraduate4.setOpaque(true);
        undergraduate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduate4ActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 310, 60));

        undergraduate5.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate5.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate5.setText("Payment");
        undergraduate5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate5.setFocusCycleRoot(true);
        undergraduate5.setOpaque(true);
        undergraduate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduate5ActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 310, 60));

        undergraduate6.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate6.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate6.setText("Send Mails");
        undergraduate6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate6.setFocusCycleRoot(true);
        undergraduate6.setOpaque(true);
        undergraduate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduate6ActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 310, 60));

        undergraduate7.setBackground(new java.awt.Color(102, 102, 102));
        undergraduate7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        undergraduate7.setForeground(new java.awt.Color(255, 255, 255));
        undergraduate7.setText("Class Allocation");
        undergraduate7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        undergraduate7.setFocusCycleRoot(true);
        undergraduate7.setOpaque(true);
        undergraduate7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undergraduate7ActionPerformed(evt);
            }
        });
        jPanel1.add(undergraduate7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 310, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void undergraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduateActionPerformed
        Home.student=1;
        this.dispose();
        Admin_Undergraduate ad =new Admin_Undergraduate();
        ad.setVisible(true);
        
    }//GEN-LAST:event_undergraduateActionPerformed

    private void undergraduate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduate1ActionPerformed
       Home.student=3;
        this.dispose();
        Admin_Lecturer ap = new Admin_Lecturer();
        ap.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_undergraduate1ActionPerformed

    private void undergraduate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduate3ActionPerformed
        Home.student=4;
        this.dispose();
        Admin_Instructor ap = new Admin_Instructor();
        ap.setVisible(true);
    }//GEN-LAST:event_undergraduate3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Home.student=2;
        this.dispose();
        Admin_Postgraduate ap = new Admin_Postgraduate();
        ap.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home hm =new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void undergraduate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduate4ActionPerformed
        Admin_Update_Subject up =new Admin_Update_Subject();
        this.dispose();
        up.setVisible(true);
    }//GEN-LAST:event_undergraduate4ActionPerformed

    private void undergraduate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduate5ActionPerformed
       this.dispose();
       Payment ww =new Payment();
       ww.setVisible(true);
    }//GEN-LAST:event_undergraduate5ActionPerformed

    private void undergraduate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduate6ActionPerformed
       this.dispose();
       Email e =new Email();
       e.setVisible(true);
    }//GEN-LAST:event_undergraduate6ActionPerformed

    private void undergraduate7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undergraduate7ActionPerformed
       Time_table t =new Time_table();
       t.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_undergraduate7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton undergraduate;
    private javax.swing.JToggleButton undergraduate1;
    private javax.swing.JToggleButton undergraduate3;
    private javax.swing.JToggleButton undergraduate4;
    private javax.swing.JToggleButton undergraduate5;
    private javax.swing.JToggleButton undergraduate6;
    private javax.swing.JToggleButton undergraduate7;
    // End of variables declaration//GEN-END:variables
}
