/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lahiru Dulanjaya
 */
public class Student_Ability extends javax.swing.JFrame {

    /**
     * Creates new form Undergradute_Ability
     */
    public Student_Ability() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choose = new javax.swing.JToggleButton();
        show_exam = new javax.swing.JToggleButton();
        show_assignment = new javax.swing.JToggleButton();
        change = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        choose.setText("Choose Subjects");
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        jPanel1.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, 50));

        show_exam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show_exam.setText(" Exam Marks");
        show_exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_examActionPerformed(evt);
            }
        });
        jPanel1.add(show_exam, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 170, 50));

        show_assignment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show_assignment.setText("Assignment Marks");
        show_assignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_assignmentActionPerformed(evt);
            }
        });
        jPanel1.add(show_assignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 170, 50));

        change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        change.setText("Change Subjects");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, 50));

        jToggleButton5.setText("BACK");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/sub.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NSBMCourseEnrollmentSystem_resources/res.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 100, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void show_assignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_assignmentActionPerformed
        try {
            this.dispose();
            Get_Assignment_Grade AG =new Get_Assignment_Grade();
            AG.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Student_Ability.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_show_assignmentActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        this.dispose();
        Choose_Subject_Undergraduate csu =new Choose_Subject_Undergraduate();
        csu.setVisible(true);
    }//GEN-LAST:event_chooseActionPerformed

    private void show_examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_examActionPerformed
        try {
            Get_Exam_Marks ex =new Get_Exam_Marks();
            this.dispose();
            ex.setVisible(true);
        } catch (SQLException ex1) {
            Logger.getLogger(Student_Ability.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_show_examActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
      this.dispose();
      Change_Subject cs =new Change_Subject();
      cs.setVisible(true);
    }//GEN-LAST:event_changeActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
      this.dispose();
      Home hm =new Home();
      hm.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Ability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Ability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Ability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Ability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Ability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton change;
    private javax.swing.JToggleButton choose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton show_assignment;
    private javax.swing.JToggleButton show_exam;
    // End of variables declaration//GEN-END:variables
}
