/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NSBMCourseEnrollmentSystem_view;

import NSBMCourseEnrollmentSystem_DB_connection.DB_connection;
import NSBMCourseEnrollmentSystem_control.class_allocation_controll;
import NSBMCourseEnrollmentSystem_model.Lab;
import NSBMCourseEnrollmentSystem_model.Room;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lahiru Dulanjaya
 */
public class Time_table extends javax.swing.JFrame {

    /**
     * Creates new form Time_table
     */
    public Time_table() {
        
            
            initComponents();
        try {
            fillcombo1();
            fillcombo2();
        } catch (SQLException ex) {
            Logger.getLogger(Time_table.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        slot = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        allocate = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sub1 = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        labdate = new javax.swing.JTextField();
        lab = new javax.swing.JTextField();
        back1 = new javax.swing.JButton();
        allocate1 = new javax.swing.JButton();
        ins = new javax.swing.JComboBox<>();
        sub2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Class Allocation");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Class Allocation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Time Slot");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 140, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Room number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Subject");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, 40));
        jPanel1.add(slot, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 160, 30));
        jPanel1.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 160, 30));

        allocate.setText("Allocate");
        allocate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocateActionPerformed(evt);
            }
        });
        jPanel1.add(allocate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 110, 30));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 160, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 140, 40));

        jPanel1.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 70, 30));

        jTabbedPane1.addTab("Class ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Lab Allocation");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 190, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel7.setText("Date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 120, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel8.setText("Subject Code");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel9.setText("Instructor Id");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel10.setText("Lab number");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel11.setText("Time Slot");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 120, 30));
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 210, 30));
        jPanel2.add(labdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 210, 30));
        jPanel2.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 210, 30));

        back1.setText("Back");
        jPanel2.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 70, 30));

        allocate1.setText("Allocate");
        allocate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocate1ActionPerformed(evt);
            }
        });
        jPanel2.add(allocate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, 30));

        jPanel2.add(ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 180, 20));

        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });
        jPanel2.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, 20));

        jTabbedPane1.addTab("Lab", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 780, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2ActionPerformed

    private void allocateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocateActionPerformed
        Room us =new Room();
        us.setRoomno(room.getText());
        us.setSubject(sub1.getSelectedItem().toString());
        us.setDate(date.getText());
        
        us.setTime(slot.getText());
        try {
            class_allocation_controll.add_room(us);
            JOptionPane.showMessageDialog(this,"Success");
        } catch (SQLException ex) {
            Logger.getLogger(Time_table.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_allocateActionPerformed

    private void allocate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocate1ActionPerformed
        Lab us =new Lab();
        us.setLabno(lab.getText());
        us.setSubject(sub2.getSelectedItem().toString());
        us.setInstuctor_id(ins.getSelectedItem().toString());
        us.setDate(labdate.getText());
        
        us.setTime(time.getText());
        try {
            class_allocation_controll.add_lab(us);
            JOptionPane.showMessageDialog(this,"Success");
        } catch (SQLException ex) {
            Logger.getLogger(Time_table.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_allocate1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        register_option r =new register_option();
        r.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time_table().setVisible(true);
            }
        });
        
    }
     private void fillcombo1() throws SQLException{
        
        String sql2 ="Select Subject_code from subject";
        
        Connection con =DB_connection.getConnection();
        Statement st = con.createStatement();
        PreparedStatement pst2 = con.prepareStatement(sql2);
        ResultSet rs2 = pst2.executeQuery();

        while(rs2.next()){
             String s = rs2.getString("Subject_code");
             sub1.addItem(s);
             sub2.addItem(s);
         }
     }
        
         private void fillcombo2() throws SQLException{
        
        String sql2 ="Select Instructer_ID from instructor";
        
        Connection con =DB_connection.getConnection();
        Statement st = con.createStatement();
        PreparedStatement pst2 = con.prepareStatement(sql2);
        ResultSet rs2 = pst2.executeQuery();

        while(rs2.next()){
             String s = rs2.getString("Instructer_ID");
             ins.addItem(s);
             
         }
        
         
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allocate;
    private javax.swing.JButton allocate1;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> ins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lab;
    private javax.swing.JTextField labdate;
    private javax.swing.JTextField room;
    private javax.swing.JTextField slot;
    private javax.swing.JComboBox<String> sub1;
    private javax.swing.JComboBox<String> sub2;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
